# Sets up application name
spring.application.name=bff

# Sets up Via cep client
viaCepClient.urlBase=https://viacep.com.br

# Sets up Brasil API cep client
brasilApiClient.urlBase=https://brasilapi.com.br

# Sets validate cep
cep.numberOfCharacters=8

# Sets up database connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bffdb
spring.datasource.username=root
spring.datasource.password=pwdmysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Sets up health check
management.endpoints.web.exposure.include: health,info